### ISSUE TITLE
Unhandled exception on mailing label query timeout

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#42]
I have a citizen who is trying to run *To Mailing Labels* on a large abutters list and the GPV is just hanging on him.  I’m getting the error below on the server side.  I’m wondering if there is some way I can configure or work around this timeout so he can make his list?  At the very least it would be nice if it could be caught reported back to the user.  Have others had this issue?

More info:
* The user was able to download the Excel version of the same list
* The list is about 400 "parcels" (stacked for condo ownership)
* The MaxNumberSelected variable in the Layer is 500.
* The server-side max is 1000.
* The error occurs after waiting for a minute or so from clicking Create.

Here is my approximation of their query, though the caveat is that the mailing label download works for me in this ma.  Maybe because I’m internal?

http://gis.cambridgema.gov/map/Viewer.aspx?state=783894434671

# Error Text
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 3/27/2015 9:42:30 AM 
Event time (UTC): 3/27/2015 1:42:30 PM 
Event ID: 1d5603c8d0994adca271ee6b004953bf 
Event sequence: 394 
Event occurrence: 2 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1/ROOT/Map-1-130719362811828185 
    Trust level: Full 
    Application Virtual Path: /Map 
    Application Path: D:\gis_website\GPV\GPV_v4.1.0\ 
    Machine name: FIDO 
 
Process information: 
    Process ID: 8324 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\GPVMapAppPool 
 
Exception information: 
    Exception type: OleDbException 
    Exception message: Query timeout expired
   at System.Data.OleDb.OleDbDataReader.ProcessResults(OleDbHResult hr)
   at System.Data.OleDb.OleDbDataReader.NextResult()
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OleDb.OleDbCommand.ExecuteReader()
   at MailingLabels.CreateLabels(String id, String fontName, Single textSize, Boolean columnMajor) in d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 127
   at MailingLabels.cmdCreate_Click(Object sender, EventArgs e) in d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 80
   at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

 
 
Request information: 
    Request URL: http://gis.cambridgema.gov/map/MailingLabels.aspx 
    Request path: /map/MailingLabels.aspx 
    User host address: 69.46.224.126 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\GPVMapAppPool 
 
Thread information: 
    Thread ID: 39 
    Thread account name: IIS APPPOOL\GPVMapAppPool 
    Is impersonating: False 
    Stack trace:    at System.Data.OleDb.OleDbDataReader.ProcessResults(OleDbHResult hr)
   at System.Data.OleDb.OleDbDataReader.NextResult()
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OleDb.OleDbCommand.ExecuteReader()
   at MailingLabels.CreateLabels(String id, String fontName, Single textSize, Boolean columnMajor) in d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 127
   at MailingLabels.cmdCreate_Click(Object sender, EventArgs e) in d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 80
   at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
 
 
Custom event details:

**Comment by seansweeney** [comment]
You can view the stored state for my recreation in the map using the following link and entering the state ID 783894434671.

http://gis.cambridgema.gov/map/DecodeSavedState.aspx

**Comment by andrewgbuck** [comment]
This ran for me in under a minute and produced 14 pages of labels. So it
doesn't look like an internal/external issue, I think.



On Wed, Apr 8, 2015 at 9:46 AM, Sean Sweeney <notifications@github.com>
wrote:

> I have a citizen who is trying to run *To Mailing Labels* on a large
> abutters list and the GPV is just hanging on him. I’m getting the error
> below on the server side. I’m wondering if there is some way I can
> configure or work around this timeout so he can make his list? At the very
> least it would be nice if it could be caught reported back to the user.
> Have others had this issue?
>
> More info:
>
>    - The user was able to download the Excel version of the same list
>    - The list is about 400 "parcels" (stacked for condo ownership)
>    - The MaxNumberSelected variable in the Layer is 500.
>    - The server-side max is 1000.
>    - The error occurs after waiting for a minute or so from clicking
>    Create.
>
> Here is my approximation of their query, though the caveat is that the
> mailing label download works for me in this ma. Maybe because I’m internal?
>
> http://gis.cambridgema.gov/map/Viewer.aspx?state=783894434671
> Error Text
>
> Event code: 3005
> Event message: An unhandled exception has occurred.
> Event time: 3/27/2015 9:42:30 AM
> Event time (UTC): 3/27/2015 1:42:30 PM
> Event ID: 1d5603c8d0994adca271ee6b004953bf
> Event sequence: 394
> Event occurrence: 2
> Event detail code: 0
>
> Application information:
> Application domain: /LM/W3SVC/1/ROOT/Map-1-130719362811828185
> Trust level: Full
> Application Virtual Path: /Map
> Application Path: D:\gis_website\GPV\GPV_v4.1.0\
> Machine name: FIDO
>
> Process information:
> Process ID: 8324
> Process name: w3wp.exe
> Account name: IIS APPPOOL\GPVMapAppPool
>
> Exception information:
> Exception type: OleDbException
> Exception message: Query timeout expired
> at System.Data.OleDb.OleDbDataReader.ProcessResults(OleDbHResult hr)
> at System.Data.OleDb.OleDbDataReader.NextResult()
> at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior
> behavior, String method)
> at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
> at System.Data.OleDb.OleDbCommand.ExecuteReader()
> at MailingLabels.CreateLabels(String id, String fontName, Single textSize,
> Boolean columnMajor) in
> d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 127
> at MailingLabels.cmdCreate_Click(Object sender, EventArgs e) in
> d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 80
> at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
> at System.Web.UI.WebControls.Button.RaisePostBackEvent(String
> eventArgument)
> at
> System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String
> eventArgument)
> at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler
> sourceControl, String eventArgument)
> at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
> at System.Web.UI.Page.ProcessRequestMain(Boolean
> includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>
> Request information:
> Request URL: http://gis.cambridgema.gov/map/MailingLabels.aspx
> Request path: /map/MailingLabels.aspx
> User host address: 69.46.224.126
> User:
>
> Is authenticated: False
> Authentication Type:
>
> Thread account name: IIS APPPOOL\GPVMapAppPool
>
> Thread information:
> Thread ID: 39
> Thread account name: IIS APPPOOL\GPVMapAppPool
> Is impersonating: False
> Stack trace: at
> System.Data.OleDb.OleDbDataReader.ProcessResults(OleDbHResult hr)
> at System.Data.OleDb.OleDbDataReader.NextResult()
> at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior
> behavior, String method)
> at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
> at System.Data.OleDb.OleDbCommand.ExecuteReader()
> at MailingLabels.CreateLabels(String id, String fontName, Single textSize,
> Boolean columnMajor) in
> d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 127
> at MailingLabels.cmdCreate_Click(Object sender, EventArgs e) in
> d:\gis_website\gpv\GPV_v4.1.0\MailingLabels.aspx.cs:line 80
> at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
> at System.Web.UI.WebControls.Button.RaisePostBackEvent(String
> eventArgument)
> at
> System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String
> eventArgument)
> at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler
> sourceControl, String eventArgument)
> at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
> at System.Web.UI.Page.ProcessRequestMain(Boolean
> includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>
> Custom event details:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppGeo/GPV/issues/42>.
>



-- 
*Andrew Buck*
*Senior Consultant*
617-447-2430 Direct | 617-447-2400 Main
Applied Geographics, Inc.
24 School Street, Suite 500
Boston, MA 02108
www.AppGeo.com

-- 
This e-mail message and any attachments may contain confidential or legally 
privileged information. If you are not an intended recipient or otherwise 
authorized to receive this message, you should not use, copy, distribute, 
disclose or take any action based on the information contained in this 
e-mail or any attachments. If you have received this message and material 
in error, please advise the sender immediately by reply e-mail and delete 
this message. Thank you on behalf of Applied Geographics, Inc. (AppGeo).

**Comment by seansweeney** [comment]
Running the mailing label stored procedure direcly in SQL Server Management Studio gives valid results, but does take 20 seconds.  The 31 Target IDs translate into 395 ownership records (and thereby 395 labels).

**Comment by pgirard** [comment]
Please verify whether this is still an issue.
